const MODAL_TYPE = {
  VERIFY_MODAL: "VERIFY_MODAL",
  IMAGE_PREVIEW_MODAL: "IMAGE_PREVIEW_MODAL",
  LISTING_FILTER_MODAL: "LISTING_FILTER_MODAL",
  CREATE_BANNER_MODAL: "CREATE_BANNER_MODAL",
  CREATE_APPOINTMENT_MODAL: "CREATE_APPOINTMENT_MODAL",
  DETAIL_APPOINTMENT_MODAL: "DETAIL_APPOINTMENT_MODAL",
  CONTRACT_MODAL: "CONTRACT_MODAL",
  CREATE_INVOICE_MODAL: "CREATE_INVOICE_MODAL",
  UPDATE_HOST_INFO_MODAL: "UPDATE_HOST_INFO_MODAL",
  CREATE_PAYMENT_INFO_MODAL: "CREATE_PAYMENT_INFO_MODAL",
  CREATE_WITHDRAWAL_REQUEST_MODAL: "CREATE_WITHDRAWAL_REQUEST_MODAL",
  BROADCAST_MESSAGE_MODAL: "BROADCAST_MESSAGE_MODAL",
};

const APPOINTMENT_STATUS = {
  PENDING: "Đang chờ",
  CONFIRMER: "Xác nhận",
  DONE: "Hoàn thành",
  CANCELED: "Hủy",
};

const RENTED_ROOM_STATUS = {
  PENDING: "Đang chờ",
  CONFIRMER: "Xác nhận",
  CANCELLED: "Hủy",
};

const RENTED_ROOM_STATUS_COLOR = {
  PENDING: "orange",
  CONFIRMER: "green",
  CANCELLED: "red",
};

const STATUS_COLOR = {
  PENDING: "orange",
  CONFIRMER: "blue",
  DONE: "green",
  CANCELED: "red",
};

const NOTIFICATION_TYPE = {
  APPOINTMENT: "APPOINTMENT",
  RECURRING_APPOINTMENT: "RECURRING_APPOINTMENT",
  REVIEW: "REVIEW",
  REVIEW_REPLY: "REVIEW_REPLY",
  REVIEW_LIKE: "REVIEW_LIKE",
  REVIEW_REPORT: "REVIEW_REPORT",
  CREATE_INVOICE: "CREATE_INVOICE",
  CANCELED_RENTED_ROOM: "CANCELED_RENTED_ROOM",
  ACCEPT_CANCELED_RENTED_ROOM: "ACCEPT_CANCELED_RENTED_ROOM",
  APPOINTMENT_SCHEDULED: "APPOINTMENT_SCHEDULED",
  BROADCAST_MESSAGE: "BROADCAST_MESSAGE",
};
const PACKAGE_TYPE = {
  ADS_PACKAGE: "ADS_PACKAGE",
  INVOICE_PACKAGE: "INVOICE_PACKAGE",
};

const WITHDRAWAL_STATUS = {
  PENDING: "Đang chờ xử lý", // Đang chờ xử lý
  APPROVED: "Đã duyệt", // Đã duyệt
  REJECTED: "Từ chối", // Từ chối
  COMPLETED: "Hoàn tất", // Hoàn tất
};

const WITHDRAWAL_STATUS_COLOR = {
  PENDING: "orange", // Đang chờ xử lý
  APPROVED: "blue", // Đã duyệt
  REJECTED: "red", // Từ chối
  COMPLETED: "green", // Hoàn tất
};

const TRANSACTION_STATUS = {
  PENDING: "Đang chờ xử lý",
  SUCCESS: " Thành công",
  FAILED: "Thất bại",
};

const TRANSACTION_STATUS_COLOR = {
  PENDING: "orange",
  SUCCESS: "green",
  FAILED: "red",
};

export {
  PACKAGE_TYPE,
  MODAL_TYPE,
  APPOINTMENT_STATUS,
  STATUS_COLOR,
  RENTED_ROOM_STATUS,
  RENTED_ROOM_STATUS_COLOR,
  NOTIFICATION_TYPE,
  WITHDRAWAL_STATUS_COLOR,
  WITHDRAWAL_STATUS,
  TRANSACTION_STATUS,
  TRANSACTION_STATUS_COLOR,
};
